version: "3.8"
#
# Services definitions
#
services:
  app:
    image: kooldev/php:8.3-nginx
    ports:
      - "${KOOL_APP_PORT:-80}:80"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global
  database:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${KOOL_DATABASE_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - database:/var/lib/mysql:delegated
    networks:
      - kool_local
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
  cache:
    image: redis:7-alpine
    volumes:
      - cache:/data:delegated
    networks:
      - kool_local
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  node:
    image: kooldev/node:20
    command: ["npm", "run", "dev"]
    ports:
      - "3001:3001"
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global
#
# Networks definitions
#
networks:
  kool_local:
  kool_global:
    external: true
    name: "${KOOL_GLOBAL_NETWORK:-kool_global}"
volumes:
  database:
  cache:
